### ISSUE TITLE
SCT testing without using multiprocessing

### ISSUE THREAD

**Issue by machow** [datacamp/pythonwhat#100]
I was thinking about python's module system, and it seems like it may be able to run SCTs with separate imports without using multiple processes. For example..

```python
import sys
base_mods = set(sys.modules.keys())

# first version of pandas
import pandas

env1_mods = set(sys.modules.keys()) - base_mods
for k in env1_mods: del sys.modules[k]

# second version
import pandas as pandas2

# they are separate modules
pandas is pandas2
# they have separate numpy modules
pandas.np is pandas2.np

# variable assignment
pandas.x = 1
pandas.np.x = 1
# not assigned to pandas 2
hasattr(pandas2, 'x')
hasattr(pandas2.np, 'x')
```

(approach taken from this [SO post](http://stackoverflow.com/questions/6507896/python-how-to-load-a-module-twice))
This would have the advantage that we wouldn't need to worry about using dill to shuttle data across processes. The above example uses a fairly hacky approach of altering sys.modules, but similar things are done in functions like `importlib.reload`. I wonder if there's a fairly principled way to do this.

**Comment by filipsch** [comment]
The reason to switch to a separate processes system inside `pythonbackend`, and consequently, inside `pythonwhat`, is because loading in modules isn't always as clean as you want it to be. We tried a bunch of things, among which `importlib.reload()`, but it didn't always work as it should. More specifically, I remember bumping into a lot of difficulties for plots (`matplotlib`, `bokeh`, etc).

The current architecture, where student and solution are totally separate, make sure that your computing enviroment is hacked around as little as possible; it's almost as if you're working in a python shell on your own system.

[I found this article, and it describes how I feel about it ;)](http://justus.science/blog/2015/04/19/sys.modules-is-dangerous.html)

If your idea can somehow solve for all that, we should definitely look into it, but I think rethinking this architecture again is not high on the priority list; we spent more than 3 weeks figuring out how to get things to work and now it all seems to work fine. If `pythonbackend` is not going to be changed in the near future, than the process-based way of working on `pythonwhat` also has to be kept for now.

**Comment by machow** [comment]
The problems laid out in that article seem to be bad behaviors if you are trying to "reload" a module (i.e. keep the same module object, but update it), but good behaviors for what pythonwhat wants to do. For example, the first demonstration shows how deleting an entry in sys.modules lets you create a new module object, which will cause problems if you simply wanted to reload it. However, pythonwhat benefits from creating two distinct sets of module objects (as in my example).

In any event, I definitely agree it is not a priority--but didn't want to forget it. I'll make a low-priority tag so it doesn't sound like I am plotting major overhauls for things that already work ;).

**Comment by machow** [comment]
closing--intriguing but not much benefit
