### ISSUE TITLE
List comprehension SCT queries: BLOCK BETA 10/07

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#102]
Hi!

1) How would I write an SCT to test this?

```python
L2 = [i**2 for i in range(0,10) if i>2]
```

Feel free to base it on this example that I wrote:

solution:

```python
L1 = [i**2 for i in range(0,10)]
```

SCT:

```python
test_list_comp(index=1,
           comp_iter=lambda: test_expression_result(),
           iter_vars_names=True)
```

2)  How would I write the SCT for the following?

```python
L3 = [i**2 if i> 5 else 0 for i in range(0,10)]
```

3) How would I test a nested list comprehension?  E.g.,

```python
matrix = [[col for col in range(5)] for row in range(5)]
```

I think the answers to these questions could be great for the wiki! I will raise another issue wrt this :-)

**Comment by machow** [comment]
The first and third case were in pythonwhat's unit tests, so I've included them below. I'm not sure about testing a conditional statement inside a comprehension, but will get back to you by tomorrow. I think in that case, you could just include a `test_if_else` in the body argument of `test_list_comp`.

I'll tag issues that are wiki-related with the docs label, so I can use a single block of time to work on putting things in the wiki each week.

1. List Comprehension with Filter
------------------------------

*** =pre_exercise_code
```{python}
x = {'a': 2, 'b':3, 'c':4, 'd':'test'}
```

*** =solution
```{python}
[key + str(val) for key,val in x.items() if isinstance(key, str) if isinstance(val, int)]
```

*** =sct
```{python}

test_list_comp(index=1,
               not_called_msg=None,
               comp_iter=lambda: test_expression_result(),
               iter_vars_names=True,
               incorrect_iter_vars_msg=None,
               body=lambda: test_expression_result(context_vals = ['a', 2]),
               ifs=[lambda: test_function_v2('isinstance', params = ['obj'], do_eval = [False]),
                    lambda: test_function_v2('isinstance', params = ['obj'], do_eval = [False])],
               insufficient_ifs_msg=None,
               expand_message=True)
            
```

2. Conditional Statement Inside List Comprehension
----------------------------------------------------
I'm not sure, let me experiment a bit....

3. Nested List Comprehension
----------------------------

*** =solution
```{python}
[[col for col in range(5)] for row in range(5)]
```

*** =sct
```{python}
test_list_comp(1, body = lambda: test_list_comp(1, body = lambda: test_expression_result(context_vals = [4])))
```

**Comment by hugobowne** [comment]
@machow thanks and double thanks for putting up with my enumerating everything with 1! (corrected)

The solution you give for 1. I have indeed seen before (it's in the wiki). It doesn't quite solve the issue, though, as it uses `test_function_v2('isinstance')` and, in my example, there is no function call in the conditional:

`L2 = [i**2 for i in range(0,10) if i>2]`

Filip and I found a great system for these types of issues: he would post the precise SCT that works in the case that I posted; this minimizes back&forth. He also had a document of best practices for raising and responding to issues and we could add this to it.

@filipsch, where is this doc? 

Looking forward to soln to 2.

Re solution to 3., this SCT indeed accepts the solution but it also accepts

`matrix = [[col for col in range(6)] for row in range(3)]`

and `matrix = [[col for col in range(1)] for row in range(5)]`, for example, among many other variations. I need a more robust SCT. For me, understanding `context_vals` better will surely help.

**Comment by filipsch** [comment]
@hugobowne @machow the doc is here
https://datacamp.atlassian.net/wiki/display/ID/IT+Documentation

**Comment by machow** [comment]
**1)** See my response to (3) below. 

*** =solution
```{python}
L2 = [i**2 for i in range(0,10) if i>2]
```

*** =sct
```{python}
test_list_comp(index = 1, body=lambda: test_expression_result(context_vals = [2]))
```

context_vals assigns a value to the looping variables (e.g. i in the list comprehension case above).  Since there is 1 looping variable for a list comprehension, context_vals in this case is a list with 1 entry. Because a dictionary comprehension has 2 looping variables (key and val in the example I gave) you would give a list with 2 entries, one for each variable.

**2)** inline if/else expressions aren't currently supported for pythonwhat, which is a problem for the second SCT: `L3 = [i**2 if i> 5 else 0 for i in range(0,10)]`. Working on a fix now (Issue #111).

**3)** [use the comp_iter sub-test argument of test_list_comp](https://github.com/datacamp/pythonwhat/wiki/test_comprehension). `test_list_comp` splits the comprehension into body, comp_iter, and ifs, so any of the examples on parts like body or ifs also apply to comp_iter (AFAIK).

**Comment by hugobowne** [comment]
1) thanks, @machow in this case, why is `comp_iter=lambda: test_expression_result()` no longer needed? Also, this SCT accepts both `L2 = [i**2 for i in range(0,10) if i>1]` and `L2 = [i**2 for i in range(0,10) if i>3]` so I need a more robust SCT

2) Thanks. Looking forward to it

3) To avoid back & forth, would you mind posting the SCT that works? This is the protocol that has worked best for myself & Filip. If you're not quite sure what it is yet, totally fine.

It may be worth while jumping on a 5minute call to get our workflow down :-)

**Comment by filipsch** [comment]
@hugobowne @machow
It's clear that list comprehensions aren't straightforward to test, but we should avoid that michael becomes a helpdesk for more challenging SCTs. 
I think the solution here is a more detailed wiki of list comprehensions, for example with the three examples that hugo mentions here. Then it's clear, and the information doesn't get lost in an issue that gets closed.

**Comment by hugobowne** [comment]
@filipsch that was precisely the point of me raising the issue; as stated in the original comment "I think the answers to these questions could be great for the wiki!"

I agree that @machow should not be a helpdesk for more challenging SCTs. After a number of discussions with @jonathancornelissen , he said I definitely should not spend more than 30min trying to write an SCT and if I do, I should raise it here. That's what I'm currently doing. You and I agreed that the response should include the correct SCT to minimize back&forth (correct me if I'm wrong).

We can all discuss this but I think the take-home is that, until the wiki is more complete (which as you know I am helping with, even by raising these issues), I will need at least a pseudo-help-desk to write more challenging SCTs. We can then use the responses to write the wiki. Thoughts?

**Comment by filipsch** [comment]
@hugobowne agreed, just wanted to clear things out.

**Comment by machow** [comment]
@hugobowne, talking was helpful! Here are the SCTs. I'm okay with trying to send a "correct" SCT in response to an issue, but if it ends up not meeting some criteria on the first try, we should use google hangouts or screenhero to pair on working out the solution. I get the feeling that unpacking each round of SCTs takes longer for both of us than just working on the same screen, and we can quickly share much more information on what's missing. Afterward, we can use the issue to move what we learned to the wiki. **Note that for the second SCT the test_if_exp is not in production yet, but should be within the next few days**

### SCT 1)

*** =solution
```{python}
L2 = [i**2 for i in range(0,10) if i>2]
```

*** =sct
```{python}
def test_multiple_contexts():
    for ii in range(5):
        test_expression_result(context_vals = [ii])

test_list_comp(index = 1, 
    body=lambda: test_expression_result(context_vals = [2]),
    ifs = [test_multiple_contexts],
    comp_iter = lambda: test_expression_result()
)
```

Note that test_multiple_contexts will use a loop to test multiple context values, in order to see whether they did the inequality correctly.

### SCT 2)

*** =solution
```{python}
L3 = [i**2 if i> 5 else 0 for i in range(0,10)]
```

*** =sct
```{python}
test_list_comp(comp_iter = lambda: test_expression_result(),
                         body = lambda: test_if_exp(
                                   body=lambda: test_student_typed(r"\s*i\*\*2\s*"),
                                   test= lambda: test_expression_result(context_vals = [6]),
                                   orelse= lambda: test_expression_result()))
))
```

### SCT 3)

*** =solution
```{python}
matrix = [[col for col in range(3)] for row in range(5)]
```

*** =sct
```{python}
def inner_list_comp():
    test_list_comp(body = lambda: test_expression_result(context_vals=[2]),
                   comp_iter = lambda: test_expression_result())
test_list_comp(body = inner_list_comp, 
               comp_iter = lambda: test_function('range'))
```

**Comment by machow** [comment]
@hugobowne added a new wiki page with a complete explanation of first example, and placeholders for the other two. Will spend a little time Monday cleaning up typos and finishing. Thoughts? I'm closing this issue since cleaning up the wiki doesn't block beta, and I don't want to become too comfortable with having "BLOCKS BETA" issues opened ;).

**Comment by hugobowne** [comment]
@machow sounds good to me!
