### ISSUE TITLE
Floating point issues when testing equality of numpy arrays

### ISSUE THREAD

**Issue by yrdatacamp** [datacamp/pythonwhat#206]
Consider [this](https://campus.datacamp.com/courses/statistical-thinking-in-python-part-2/introduction-to-hypothesis-testing?ex=11) exercise. There are multiple ways to create `translated_force_b`. However, as shown below, numpy does not consider `a` and `b` to be equal (seemingly because of floating point precision issues). As a result, `test_object()` and `has_equal_ast()` would not accept a solution with `b`, if the solution code had `a`.

This order of operations should not matter, and students should be able to create the array in both ways. Something like [`numpy.testing.assert_almost_equal()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_almost_equal.html) may be needed to test these kinds of cases.

![screenshot 2017-04-20 17 40 08 1](https://cloud.githubusercontent.com/assets/20912644/25336878/71d9db8c-28c7-11e7-9c22-fb913d86b518.png)

cc @hugobowne

**Comment by machow** [comment]
`Ex().has_equal_value(code = "np.testing.allclose(a)")`

**Comment by yrdatacamp** [comment]
Thanks! This successfully resolves the issue. However, it's also an ideal example of the need for improved default messaging for `has_equal_value()`, raised in https://github.com/datacamp/pythonwhat/issues/208.

Without specifying a custom feedback message using the `incorrect_msg` parameter, this is the default error message, which is intimidating and unhelpful: 
![screenshot 2017-04-25 12 40 40](https://cloud.githubusercontent.com/assets/20912644/25399860/c6fe7eea-29be-11e7-85bf-f3779f7f9657.png)

As far as this particular issue goes, I'm fine with this solution. Since it's not something that comes up often, it's lower in priority compared to the other issues. That said, it's still worth adding this approach to the documentation.

**Comment by machow** [comment]
@yrdatacamp added to pythonwhat course tutorial docs [float exercise](https://github.com/datacamp/courses-pythonwhat-tutorial/blob/master/chapter1.md#float)

**relevant piece below...**

<pre>
# NOTE on floating point comparisons booby traps ---------------------------
# floating point comparisons can return false, even when two sets of
# operations are mathematically equivalent. For example, x and y are
# not equal in Python
#
#   a = [1.1, 1.2, 1.3]
#   x = (sum(a[:-1])/3 + a[-1]/3)     # 3.5999999999
#   y = (a[0]/3 + sum(a[1:])/3)       # 3.6
#   x == y                            # False
#   round(x, 10) == round(y, 10)      # True
#
# In order to flexibly test for equivalence in these cases, you can
# round the results to a desired decimal place.
# For example, to test a floating point variable x,
#   Ex().has_equal_value(expr_code = 'round(x, 10)')
</pre>

**Comment by machow** [comment]
closing, but have opened an issue for adding more flexibility to equality checks #218
