### ISSUE TITLE
issue with `test_function()` on `pickle.load()`

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#23]
issue with `test_function()` on `pickle.load()`  -- also had the issue using `test_correct`
https://campus.datacamp.com/courses/1167/2628?ex=3

<img width="1268" alt="screenshot 2016-06-14 13 35 53" src="https://cloud.githubusercontent.com/assets/4182382/16053722/0218831a-3238-11e6-8d13-10158e8a6bb7.png">

this issue will block beta testing. please all feel free to suggest workarounds!

**Comment by vincentvankrunkelsven** [comment]
(note to self) Argument file is not the same in environments. Should improve `test_function()` so arguments can be checked non-evaluated easily.

**Comment by vincentvankrunkelsven** [comment]
When we push the fix to production, this SCT will do:
```
# Test: import pickle package
import_msg = "Did you import `pickle` correctly?"
test_import("pickle", same_as = True, not_imported_msg = import_msg, incorrect_as_msg = import_msg)

# For testing statements inside with statement
def test_with_body():
    test_object("d")
    test_function("pickle.load", do_eval = False) # CHANGE THIS

# Test: Context manager
test_with(
    1,
    context_vals = True,
    context_tests = lambda: test_function("open"),
    body = test_with_body
)

# Test: print() statement
test_function("print", index = 0) # CHANGE THIS

# Test: print() statement and call to type()
type_msg = "Print out the type of `d` as follows: `print(type(d))`."
test_function("type", index = 0, incorrect_msg = type_msg) # CHANGE THIS
test_function("print", index = 1, incorrect_msg = type_msg) # CHANGE THIS

success_msg("Awesome!")
```

**Comment by vincentvankrunkelsven** [comment]
The reason you have to use `do_eval = False` here is because the evaluation of the object resulting from `open('data.p', 'rb')` will not be the same in student and solution environment (try it: `open('data.p', 'rb') == open('data.p', 'rb')` will return `False`). When you do `test_function('pickle.load')` you're automatically testing al the arguments that are defined in the solution. This means you're comparing the evaluated value of `file` in the solution and student environment, which will fail (remember -- `open('data.p', 'rb') == open('data.p', 'rb')` will return `False`). By using `do_eval = False`, you will make pythonwhat compare the unevaluated value of the argument, which is the argument name: `file`. It will be the same.

**Comment by hugobowne** [comment]
wohooo!
