### ISSUE TITLE
Solution not accepted with test_correct 

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#24]
https://campus.datacamp.com/courses/1167/2628?ex=17

<img width="1265" alt="screenshot 2016-06-14 14 02 30" src="https://cloud.githubusercontent.com/assets/4182382/16053894/aee9173a-3238-11e6-845b-a1fd24224fc1.png">

```
#Test: call to scipy.io.loadmat() and 'mat' variable
test_correct(
    lambda: test_object("mat"),
    lambda: test_function("scipy.io.loadmat")
)
```

this issue will block beta testing. please all feel free to suggest workarounds!

**Comment by hugobowne** [comment]
i have what looks like a similar issue here but it may be different:

https://campus.datacamp.com/courses/1167/2631?ex=12

<img width="1274" alt="screenshot 2016-06-14 14 34 00" src="https://cloud.githubusercontent.com/assets/4182382/16054873/0f3a489e-323d-11e6-841c-7b7d80183c9b.png">

**Comment by vincentvankrunkelsven** [comment]
When the Fix is pushed to production, use `do_eval = False` for the relevant `test_function`s, like I proposed in #23.

**Comment by vincentvankrunkelsven** [comment]
For your second problem, basically same type of problem. Inside `test_correct()` you're doing `test_object("auth")`. The auth object: `tweepy.OAuthHandler(consumer_key, consumer_secret)` is never equal (try it: `tweepy.OAuthHandler(consumer_key, consumer_secret) == tweepy.OAuthHandler(consumer_key, consumer_secret)` returns `False`). So it can't be equal in the student and solution code either, that's why it's always returning the Incorrect Submission message. Basically each time you're comparing objects with `test_object()` or comparing arguments with `test_function()`, if the objects are instances of specific classes which don't have a nice implementation of the `==` operator (using `__eq__`), they will never match. 

For this exercise I would use this SCT:
```
# Test: import tweepy
import_msg = "Did you correctly import the required package?"
test_import("tweepy", same_as = True, not_imported_msg = import_msg, incorrect_as_msg = import_msg)

# Test: Predefined code
predef_msg = "You don't have to change any of the predefined code."
test_object("access_token", undefined_msg = predef_msg, incorrect_msg = predef_msg)
test_object("access_token_secret", undefined_msg = predef_msg, incorrect_msg = predef_msg)
test_object("consumer_key", undefined_msg = predef_msg, incorrect_msg = predef_msg)
test_object("consumer_secret", undefined_msg = predef_msg, incorrect_msg = predef_msg)

# Test: call to tweepy.OAuthHandler() and 'auth' variable
test_object("auth", do_eval = False)
test_function("tweepy.OAuthHandler")
# --> Basically just checks if the student defined the object `auth` and if the student used the function `tweepy.OAuthHandler` correctly. That should be enough.

# Test: call to auth.set_access_token()
test_function("auth.set_access_token")

success_msg("Awesome!")
```

**Comment by hugobowne** [comment]
will check this one out tuesday 06/21

**Comment by hugobowne** [comment]
this all works now 👍
