### ISSUE TITLE
check_object() not working for list of data frames

### ISSUE THREAD

**Issue by avaepark** [datacamp/pythonwhat#269]
`check_object().has_equal_value()` is not working correctly when the object is a list of data frames. 

## PEC
```{python}
import glob
import pandas as pd
import urllib.request
urllib.request.urlretrieve('https://s3.amazonaws.com/assets.datacamp.com/production/course_5368/datasets/inflammation-01.csv', 'inflammation-01.csv')
urllib.request.urlretrieve('https://s3.amazonaws.com/assets.datacamp.com/production/course_5368/datasets/inflammation-02.csv', 'inflammation-02.csv')
urllib.request.urlretrieve('https://s3.amazonaws.com/assets.datacamp.com/production/course_5368/datasets/inflammation-03.csv', 'inflammation-03.csv')

inflam_files = glob.glob('*.csv')
```

## Solution

```{python}
dfs_comp = [pd.read_csv(f) for f in inflam_files]
print(dfs_comp)
```

## SCT
```
Ex().check_object("dfs_comp").has_equal_value()
```

## Error message

![screen shot 2018-06-07 at 10 58 27 am](https://user-images.githubusercontent.com/39744265/41108135-c76c531a-6a41-11e8-854c-8828421843dc.png)

**Comment by filipsch** [comment]
You can use the following SCT, that overrides how `has_equal_value()` compares the the `dfs_comp` object from the student process and the `dfs_comp` object from the solution process:

```python
def compare(x, y):
    # check if same length
    if (len(x) != len(y)): return False

    # check if underlying data frames are equal
    for i in range(len(x)):
        if not x[i].equals(y[i]): return False

    return True

Ex().check_object("dfs_comp").is_instance(list).has_equal_value(func = compare)
```

The underlying reason: we have custom equality checks for pandas data frames, but because this is a list of pandas data frames, `pythonwhat` didn't use those equality checks. This manual compare function makes sure that this _is_ done.

cc @sumedh10

**Comment by filipsch** [comment]
@avaepark great issue by the way, super easy for me to reproduce and figure out a fix.
