### ISSUE TITLE
Test DataFrame methods

### ISSUE THREAD

**Issue by avaepark** [datacamp/pythonwhat#270]
Unable to test the following DataFrame methods with `check_function()`

# groupby

## PEC
```{python}
import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset('tips')
```

## SOLUTION
```{python}
# Mean tip by sex
print(df.groupby('sex')['tip'].mean())

# Mean tip by sex and time
print(df.groupby(['sex', 'time'])['tip'].mean())
```

## SCT

```
# Sumedh expected the following to work
Ex().check_function("df.groupby")
```

based on  [this](https://github.com/datacamp/courses-visualizing-time-series-python/blob/9bba1b6909f5352da6767606d5ba3c2c081a80e7/chapter5.md#monthly-trend). 

But the error says `df.groupby` was not found in the solution environment. Also, not sure how to test the entire command. 

# reorder_categories

## PEC

`@pre_exercise_code`

```{python}
import seaborn as sns
import pandas as pd
tips = sns.load_dataset('tips')

tips.total_bill = tips.total_bill.astype(str)
tips.tip = tips.tip.astype(str)
tips.sex = tips.sex.astype(str)
tips.smoker = tips.smoker.astype(str)
tips.day = tips.sex.astype(str)
tips.time = tips.time.astype('category')
tips['size'] = tips['size'].astype(str)

```

## Solution
```{python}
# Order the time category so lunch is before dinner
tips.time = tips.time.cat.reorder_categories(['Lunch', 'Dinner'], ordered=True)
```

## SCT

```
# Test time category
Ex().check_function("tips.time.cat.reorder_categories").multi(
        check_args(0).has_equal_value("msg"),
        check_args(1).has_equal_value("msg"))
```

![screen shot 2018-06-07 at 12 17 15 pm](https://user-images.githubusercontent.com/39744265/41112396-cd398aa0-6a4c-11e8-9621-0789acef45b5.png)

**Comment by avaepark** [comment]
On further digging, looks like the following code works: 

```
Ex().test_or(has_equal_ast("",
                           code="df.groupby('sex')['tip'].mean()",
                           exact=False),
             has_equal_ast("",
                           code="df.groupby('sex').tip.mean()",
                           exact=False))
```

Is this the recommended approach when dealing with methods?

**Comment by filipsch** [comment]
@avaepark 

I looked into it, and it seems that the checking of method calls is seriously bugged in `check_function()`, but also in `test_function_v2()` (as the use the same underlying (broken) parsing logic).

This is not something that can be fixed and deployed in a rush, so I suggest to work around this for now.

The code that you suggest is very close to basically regex checking (checking the AST instead of a simple regex), so it's not very robust. It wouldn't pass the following submission, for example:

```python
x = df.groupby('sex')
print(x['tip'].mean())
```

Instead, I would use:

```python
Ex().check_function("print", index=0, append_msg = '', signature = False).check_args(0).has_equal_value("Informative message")
```

Some comments about this:

- The above is rerunning the expression used to set the argument. In this case, this expression is the method chain. So it's executing the method chain in both student and solution and comparing the results.
- Because your check can't go more detailed for now, I would make sure your feedback message is informative enough so people can figure it out.
- You can use the same approach for the other method calls as well.
- I will close this issue and create a separate issue to investigate and improve the method call checking logic.

For future reference, this is how I tested it when in the `pythonwhat` repo:

```python
import pytest
import helper

def test_normal_pass():
    code = """
import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset('tips')

# Mean tip by sex
print(df.groupby('sex')['tip'].mean())

# Mean tip by sex and time
print(df.groupby(['sex', 'time'])['tip'].mean())
"""
    data = {
		"DC_PEC": """
import seaborn as sns
import pandas as pd
import numpy as np

df = sns.load_dataset('tips')
""",
		"DC_CODE": code,
        "DC_SOLUTION": code,
		"DC_SCT": """
Ex().check_function("print", index=0, append_msg = '', signature = False).check_args(0).has_equal_value("Informative message")
"""
	}
    output = helper.run(data)
    assert output['correct']
```


TIP: use `python` behind triple backticks in a GitHub issue to get syntax highlighting.
