### ISSUE TITLE
General Q: how do we get SCTs to point more specifically to the actual error?

### ISSUE THREAD

**Issue by klmedeiros** [datacamp/pythonwhat#310]
I'm working on improving "Natural Language Processing Fundamentals in Python" and came across an exercise where many of the students have noted "unhelpful feedback" and I was able to replicate some of their problem. 

Here's the entire solution for the exercise (ch2ex10):
```
# Save the fifth document: doc
doc = corpus[4]

# Sort the doc for frequency: bow_doc
bow_doc = sorted(doc, key=lambda w: w[1], reverse=True)

# Print the top 5 words of the document alongside the count
for word_id, word_count in bow_doc[:5]:
    print(dictionary.get(word_id), word_count)
    
# Create the defaultdict: total_word_count
total_word_count = defaultdict(int)
for word_id, word_count in itertools.chain.from_iterable(corpus):
    total_word_count[word_id] += word_count

# Create a sorted list from the defaultdict: sorted_word_count 
sorted_word_count = sorted(total_word_count.items(), key=lambda w: w[1], reverse=True) 

# Print the top 5 words across all documents alongside the count
for word_id, word_count in sorted_word_count[:5]:
    print(dictionary.get(word_id), word_count)
```

I made a mistake while evaluating the instructions and forgot to call `items()` on `total_word_count`, and got this feedback:
![screen shot 2018-07-05 at 9 55 41 am](https://user-images.githubusercontent.com/16199504/42327411-9d77329c-8039-11e8-941d-b6f05e609176.png)

The first `for` statement isn't related to making an error down on `sorted_word_count` at all, so my question is a bit general, since I've seen this in other places too, but is there a good way to get the SCTs to point more specifically to where errors are being made? I added an SCT that is checking the `sorted_word_count` object itself, and if I make the same mistake, it still throws the error shown.

Thanks!

**Comment by filipsch** [comment]
@klmedeiros this is because `word_id` is being used over and over as the iterator variable. By the time the entire submission has executed, `word_id` will be equal to the last word_id in `sorted_word_count[:5]` (from the last for loop).

Then, when the SCT is going to do comparisons, it will rerun the arguments of the `print()` call, which are `dictionary.get(word_id)` and `word_count` in this case. `word_id` here will no longer be the `word_id` it was when the first for loop was running.

If the student coded things correctly, this is not really a problem, because `word_id` will be the same for both student and solution (although it's not the `word_id` from the first for loop).

If the student didn't code things up further down the script though, things go wrong.

To solve this:

- Set explicit context values with `set_context()` instead of blindly falling back on whatever has been set by running the script:

  ```python
  Ex().check_for_loop().check_body().\
      set_context(word_id = 'something_meaningful', word_count = 'something_else_meaningful').\
      check_function('print').check_args(0).has_equal_value()
  ```

- Do not test the actual values of the expressions, by using `has_equal_ast()` instead of `has_equal_value()`, although this is not very robust.

- Avoid the 'overriding' of python variables alltogether, i.e. use `word_id2` and `word_id3` in the subsequent for loops. Overall, overriding of variables is not good practice.

I'm starting to realize that I should write a 'common pitfalls' article with some of these thorny examples. I'll make sure it happens soon!
