### ISSUE TITLE
Unable to check train_test_split()

### ISSUE THREAD

**Issue by nicksolomon** [datacamp/pythonwhat#322]
I'm getting a weird error when I try to test the `train_test_split()` function from `sklearn.model_selection` directly. The error is

![image](https://user-images.githubusercontent.com/20202701/43095225-1a1c4894-8e83-11e8-95b5-906fcfcb6c0a.png)

Here's an example:
### PEC
```python
import pandas as pd
from sklearn.model_selection import train_test_split
wine = pd.read_csv("https://s3.amazonaws.com/assets.datacamp.com/production/course_6576/datasets/wine_types.csv")
X = wine.drop("Type", axis=1)
y = wine["Type"]
```

### Solution
```python
# Split the dataset and labels into training and test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y)
```

### SCT
```python
Ex().check_function("sklearn.model_selection.train_test_split").multi(
    check_args(0).has_equal_value(),
    check_args(1).has_equal_value()
)
```

**Comment by filipsch** [comment]
@nicksolomon I figured it out: according to the [docs](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html), `train_test_split()` takes `*arrays` and `**options` as arguments. 

You can read the relevant pythonwhat docs for this [here](https://pythonwhat.readthedocs.io/en/latest/articles/checking_function_calls.html#args-example).

### Option 1

Avoid signature matching, so that you can refer to it the way you did right now:

```python
Ex().check_function("sklearn.model_selection.train_test_split", signature=False).multi(
    check_args(0).has_equal_value(),
    check_args(1).has_equal_value()
)
```

### Option 2

Refer to the arguments through the starargs:

```python
Ex().check_function("sklearn.model_selection.train_test_split").multi(
    check_args(['arrays', 0]).has_equal_value(),
    check_args(['arrays', 1]).has_equal_value()
)
```

I verified both approaches and they both work. However, the second approach is more robust.

I have taken note that this can be pretty confusing, and I'll try to improve the docs accordingly.
