### ISSUE TITLE
test_function not working

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#53]
test_function is not working for the sqlalchemy function `Table()`. To be precise, the solution code is NOT accepted. This is what the SCT responds:

<img width="511" alt="screenshot 2016-07-17 12 43 41" src="https://cloud.githubusercontent.com/assets/4182382/16902160/28eb7ce2-4c1c-11e6-8906-01c61021631b.png">

[this is the exercise](https://campus.datacamp.com/courses/1380/3286?ex=12) and [this is the repo branch](https://github.com/datacamp/courses-introduction-to-relational-databases-in-python/blob/SCT_test/chapter1.md)

**Comment by hugobowne** [comment]
Note: there is also an issue with `test_function('select')` in the same exercise. as the issue may be different, would you like me to raise another issue?

**Comment by filipsch** [comment]
Please also reference the line inside the chapter file on GitHub; you can do that by clicking the ruler next to the document; gives you a link with ends with LX, where X is the line that has to be scrolled to.

**Comment by filipsch** [comment]
Hey @hugobowne, I found the issue; the parser couldn't handle the `from import sqlalchemy import Table` way of makign functions available; I've pushed an [update to the master branch](https://github.com/datacamp/pythonwhat/commit/caaeb9c7b7f894c22f19766e8a5c7ed1a4282ec4) and expect this fix to go live later this week (I'd say wednesday).

From then on, you can use the following call to test the function:

```
test_function('sqlalchemy.Table', do_eval = False)
```

Note that you need `sqlalchemy.Table`, not simply `Table`.

**This fix can have some effect on the SCTs of the importing data course that's currently live; I'll look after the SCTs so that everything keeps running smoothly for the students.**

**Comment by filipsch** [comment]
Updated the wiki with a NOTE:
https://github.com/datacamp/pythonwhat/wiki/test_function#example-3-custom-feedback

**Comment by hugobowne** [comment]
@filipsch great thanks

**Comment by hugobowne** [comment]
@filipsch will give lineks with lines in future thx sorry forgot!  rest of workflow mow seems to work well ;-)
