### ISSUE TITLE
testing lambda functions: block beta testing 08/17

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#55]
can we test the definition and use of lambda function?

E.g.

```
# Define echo_word as a lambda function: echo_word
echo_word = (lambda word1, echo: word1 * echo)
```

and

```
# Create a list of strings: spells
spells = ['protego', 'accio', 'expecto patronum', 'legilimens']

# Use map() to apply a lambda function over spells: shout_spells
shout_spells = map(lambda item: item + '!!!', spells)
```

**Comment by vincentvankrunkelsven** [comment]
Testing the definition is not possible ATM but I think you can test the functionality of a lambda function using `test_expression_result()`. 

E.g.
```
test_expression_result(expr_code="echo_word('ECHO!!', 5)")`
```
This will compare the result of `expr_code` in the student and solution environment (and since these environments contain the defined lambda expression, it tests if they return the same).

**Comment by filipsch** [comment]
@vincentvankrunkelsven thanks for sharing this.
@hugobowne The workaround that Vincent mentions indeed allows you to indirectly test a lambda functions, but it's not ideal.
 
I'll try to look into a decent way of providing support for lambda functions by start of week next week (August 8).

**Comment by filipsch** [comment]
@hugobowne a function `test_lambda_function()` that looks very much like `test_function_definition()` has been added; it'll be on staging soon. 
[Wiki article will be added here](https://github.com/datacamp/pythonwhat/wiki/test_lambda_function)

**Comment by filipsch** [comment]
Will go live tomorrow
