### ISSUE TITLE
Nested functions issue: BLOCK BETA 9/7

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#72]
I am having issues writing SCTs for nested functions.

See exercise [here](https://campus.datacamp.com/courses/1533/3850?ex=14) and [code here](https://github.com/datacamp/HBA-python-problem-playground/blame/master/chapter1.md#L919).

Currently `test_function_definition("inner", results=[("Hi")])` does NOT work in `inner_test()` defn, nor does `test_student_typed()`in `inner_test()` -- you can see I am now testing the student_typed `return` statement outside. Is this related to the current bug?

Also, changing `def inner` to `def inner1` in solution breaks DataCamp: current bug also, I presume?

Also (important for me), I don't think I should need to use `test_student_typed()` to make sure the inner function returns what it should but I haven't been able to test the inner function return value correctly in any other way yet.

thoughts?

**Comment by filipsch** [comment]
@hugobowne

You were right that there were some unforseen issues with `test_function_definition`, because the `return()` statement of the body of a function definition is replaced by something else so that you can safely execute the entire body without getting errors like 'using return outside function body'. Because of this replacement, the code was not appropriately extracted from the function body itself. But that's fixed now, and will be solved in the update of Mnday september 5.

The following SCT will work then (only the part on the function definition is included):

```python
def inner_test():
    def inner_body_test():
        test_student_typed("word\s*\+\s*['\"]!!!['\"]", not_typed_msg = "Have you correctly coded `inner()`?")
    test_function_definition("inner", body = inner_body_test)

test_function_definition("three_shouts",
                         body= inner_test,
                         results = [("hi", "there", "pretty")])
```

(It can be that you have to 'double escape' the double quotes in the regex pattern of `test_student_typed()`.)

One big thing to note here: You CANNOT use `results` inside the `test_function_definition("inner")` part. That's because the `results`, `outputs` and `errors` arguments go look for the value of the `inner` object in the solution environment. But because it's a function definition inside another function definition, it's not avialable in the global environment (because of scoping). So you can't do any 'runs' of this function definition for different inputs. 

With the already specced out granular system of pythonwhat, this will probably be possible, but that's not coming before the retreat I think.

**Comment by hugobowne** [comment]
thx. I'll try this when it's on production.
