### ISSUE TITLE
Nested functions issue III: BLOCK BETA 9/7

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#74]
Last issue on nested function (eek; I hope!) .

[Here is exercise](https://campus.datacamp.com/courses/1533/3850?ex=15)

[Here is code](https://github.com/datacamp/HBA-python-problem-playground/blame/master/chapter1.md#L1115)

I've nearly got it, however

`test_object_expression("echo_word")` doesn't seem to quite work. If I remove inner function, it's fine. This is in agreement with what I can see in the error thrown in faded background here:

<img width="683" alt="screenshot 2016-09-02 16 36 59" src="https://cloud.githubusercontent.com/assets/4182382/18194791/8fb40faa-712b-11e6-8b38-325cb3c97015.png">

I had hoped that `test_object_expression()` would only check out "echo_word" after running the function and the nonlocal business woudn't matter but that doesn't seem to be the case.

the subtleties of scoping, presumably: thoughts?

**Comment by filipsch** [comment]
@hugobowne This happened because when you use `test_object_expression("echo_word")`, the entire function body of `echo_shout`, so in this case:

```python
echo_word = word*2
print(echo_word)
def shout():
    global echo_word
    echo_word = echo_word + '!!!'
shout()
print(echo_word)
```

Will be executed.

However, if you try this yourself on your local system, you'll see that Python complains, because 'no binding for nonlocal 'echo_word' found'. 

I implemented a fix so that the `nonlocal` statements are converted into `global` in the parse tree. That way, if you execute the entire function body, there's no problem.

The 'string representations' of these function bodies are not affected, so you can still use stuff like `test_student_typed("nonlocal")`, would you want to do so.

Like the other stuff, available from September 5th, hopefully.

OK?

**Comment by hugobowne** [comment]
thx. I'll try this when it's on production. Can you let me know when that's the case?
