### ISSUE TITLE
test_if_else with test_function_definition

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#76]
I have a `test_if_else()` inside a `test_function_definition()`.

I have tried to use `test_object_after_expression()` but something funky is happening with `context_vals` and the `test_if_else()` because the conditional is on a function argument.

I have got a semi-workaround using `test_student_typed()` and have commented out the `test_object_after_expression()` lines. Any suggestions as to how to get them to work?

here is SCT:  https://github.com/datacamp/courses-pythonista-data-science-toolbox-I/blame/SCT_edits/chapter2.md#L800

here is exercise: https://campus.datacamp.com/courses/1692/4443?ex=11

**Comment by filipsch** [comment]
I've made a fix so that the context values of 'surrounding structures', such as in this case, where the if-else is inside a function definition, is inherited, so that you can also use context vals inside the test of the body of the if-else statement.

However, this fix won't do it, because the body of the `if` depends on `echo_word`, and the definition of that object is outside of the if body, so if `test_object_after_expression` runs the body, it will not know the value of `echo_word`.

The workaround I suggest, is to use the following in `test_body()` and `test_orelse()`

```
test_object_after_expression("echo_word_new", extra_env = {'echo_word': 'Hey!!! Hey!!!'})
```

This bypasses the need for `context_vals` in the first place.

By the way, I suggest you also use a `test_correct()` here, so that you don't go checking the if else statement if the output of the function is correct. This would then be the barebones version of the SCT:

```python
def inner_test():
    def check_inner():
        test_object_after_expression("echo_word", context_vals = ["Hey!!!", 2, True])
        test_object_after_expression("echo_word_new", context_vals = ["Hey!!!", 2, True])

    def diagnose_inner():
        def test_test():
            test_expression_result({"intense": True})
            test_expression_result({"intense": False})

        def test_body():
            test_object_after_expression("echo_word_new", extra_env = {'echo_word': 'Hey!!! Hey!!!'})

        def test_orelse():
            test_object_after_expression("echo_word_new", extra_env = {'echo_word': 'Hey!!! Hey!!!'})

        test_if_else(index = 1, test = test_test, body = test_body, orelse = test_orelse)

    test_correct(check_inner, diagnose_inner)

test_function_definition("shout_echo", body = inner_test)
```

Notice that in this case, the following submission would also be accepted:

```python
def shout_echo(word1, echo = 1, intense = False):
    echo_word = word1 * echo
    if intense is True:
        a = echo_word.upper() + '!!!'
    else:
        a = echo_word + '!!!'

    echo_word_new = a
    return echo_word_new
```

**Comment by hugobowne** [comment]
@filipsch great suggestion. I'll try it. I was planning on using a `test_correct()` so great minds think alike
