### ISSUE TITLE
test_function_defintion with *args, **kwargs: BLOCK BETA 9/9

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#78]
I'm writing SCTs for user-defined functions, in which they use *args & **kwargs.

SCT here: https://github.com/datacamp/courses-pythonista-data-science-toolbox-I/blame/SCT_edits/chapter2.md#L948

Exercise here: https://campus.datacamp.com/courses/1692/4443?ex=12

If I pass the parameter `args` instead of `*args` (very likely), the SCT throws this to the student:

<img width="1269" alt="screenshot 2016-09-05 18 52 11" src="https://cloud.githubusercontent.com/assets/4182382/18242502/fd46e950-7399-11e6-94f3-0086be5c2bf5.png">

I wanted to check if I was using `extra_envs` correctly but I keep getting the 'line end' error described in #77. Eventually, I'll use a `test_correct()` and test the for loop, if necessary, but i wanted to raise the `*args` issue now as you may have thought about it.

Similarly, in the next exercise, the student will use `**kwargs`:
https://campus.datacamp.com/courses/1692/4443?ex=13

thanks for your attention!

**Comment by filipsch** [comment]
There's no support for `*args` and `**kwargs` in `test_function_definition()`. I'll look into it.

**Comment by filipsch** [comment]
@hugo the `line end` error should be solved soon. About supporting `*args` and `**kwargs`: this is though, and I need some more pointers. 

1. You want to check whether they specified `*args` and `**kwargs`, right? You also want to check defaults? That would complicate things, but ideally, yes.. ?
2. You also want to be able to pass more than tuples or lists to `test_function_definition` arguments `results`, `outputs` and `errors`. Because also want to support keyword arguments, right?

**Comment by hugobowne** [comment]
1. yes, ideally. I don't think that I need default `*args`, `**kwargs` for my course but i'll need to double-check
2. yep!

**Comment by filipsch** [comment]
This is going to be a challenge, I like that! Will keep you notified. Sept 9 (it's today) will be a bit tight, though...

**Comment by hugobowne** [comment]
hahah yep BETA TESTING date changed due to delays: hoping now 09/15 :-)

**Comment by filipsch** [comment]
Normally it's there, I'll update the wiki of `test_function_definition()`.
