### ISSUE TITLE
Testing user-defined function with DataFrame arg: BLOCK BETA 09/15

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#83]
I am trying to write an SCT for a function which takes a DataFrame as an an argument.

I can't seem to figure out what to pass `results` in `test_function_definition()`.

See [here](https://www.datacamp.com/teach/edit/repositories/463/branches/SCT_edits)

It's the exercise in Ch1 that begins on line868 (trying a new way of referencing code on the teach app: let me know if it works).

I cannot pass `results` a DataFrame but would like to :-)

It's related to #70 (turning that exercise into a function).

a related question: is it possible to avoid using the `results` argument here?

**Comment by filipsch** [comment]
@hugobowne the current implementation of `test_function_definition` works fine, but the SCT is pretty hard to write (i removed custom messages):

```python
def inner_test():
    import pandas as pd
    test_df = pd.DataFrame({'a': [0,1], 'lang':[2,2]})
    test_object_after_expression("col", context_vals = [test_df, 'lang'])
    def test_for_iter():
        test_expression_result(extra_env = {'col': pd.Series([2, 2])})

    def test_for_body():
        test_object_after_expression("langs_count",
                                     extra_env = {'langs_count': {"en": 1}},
                                     context_vals = ['et'])
        test_object_after_expression("langs_count",
                                     extra_env = {'langs_count': {"en": 1}},
                                     context_vals = ['en'])

    test_for_loop(
        index=1,
        for_iter=test_for_iter,
        body=test_for_body
    )

    test_object_after_expression("langs_count", context_vals = [test_df, 'lang'])

import pandas as pd
test_df = pd.DataFrame({'a': [0,1], 'lang':[2,2]})
test_function_definition(
    "count_entries", body = inner_test,
    results=[[test_df, 'lang']],
)
test_function("count_entries")
test_object("result")
test_function("print")

success_msg("Great work!")
```

I had to change quite some stuff in `inner_test` so that you set the correct context vals. Also, I've used `test_df`; it works fine to pass this as an argument in `results`.

Notice that you can simply use a list of lists to specify `results`, `outputs` or `errors` in `test_function_definition`, I guess this is easier. I'll update the wiki accordingly.

It's perfectly possible to avoid `results` here; basically, you're testing the same thing in different ways: you're using `test_object_after_expression()` inside `inner_test`, to test the value of `langs_count`, but that's almost the same as calling the function with certain arguments and checking whether it returns the correct value. The only difference is, is that the latter actually returns `langs_count`, and it is agnostic of the names of the variables inside the scope of the function definition.

**Comment by hugobowne** [comment]
@filipsch ok thx i'll give this a try. I haven't quite parsed your entire response yet but I have a question: i want to use `test_function_definition()` using `results=` the Twitter DataFrame in the exercise. Is this possible or would you not advise it?

**Comment by filipsch** [comment]
@hugobowne That is perfectly fine, but you'll have to manually create this data frame inside the SCT code; the student code, solution code and actual SCT code are all executed in separate processes, so the SCT has no clue about the existence of the DataFrame that's created in the student code. You even have to download the file again; all these processes also run inside their own directory...

**Comment by hugobowne** [comment]
@filipsch yep i got that; wanted to make sure it was possible. SCTs haven't always responded well to my trying `import pandas as pd`, etc.. but I'll try again
