### ISSUE TITLE
test_function_definition: can we test_object within it?

### ISSUE THREAD

**Issue by hugobowne** [datacamp/pythonwhat#9]
hi!  i love that you can `test_function` within `test_function_definition`:  can we also test objects within the scope?

@franciscastro tried but to no avail yet. If so, could you possibly provide a quick example of usage in the case of this exercise:

https://campus.datacamp.com/courses/1113/2464?ex=3
 thanks!

**Comment by vincentvankrunkelsven** [comment]
Have you tried using `test_object_after_expression()`?

```
test_function_definition('shout', body = lambda: test_object_after_expression('shout_word'))
```

**Comment by vincentvankrunkelsven** [comment]
`test_object()` only works in the global scope. 

However Filip and me have been thinking about making the notation to test things more 'Pythonic'. These functions are actually in this kind of format (with the lambda/custom defined functions and stuff), because that's how it was done in R. However in Pyhton in might make more sense to write the test you'd like to do like this:

```
test_function_definition('shout').get_body().test_object('shout_word')
```

This could make testing in Python more "object-oriented-ish". You could go to a notation like this:

```
shout_def_body = test_function_definition('shout').get_body()
shout_def_body.test_object('shout_word')
shout_def_body.test_function(...)
shout_def_body.test_if_else(...)
```

I'm sure we'll discuss this further when Filip's back. Might be interesting to include you in that conversation to get your feedback.

**Comment by hugobowne** [comment]
@franciscastro and I will try `test_object_after_expression()` and let you know how it goes!

**Comment by vincentvankrunkelsven** [comment]
@hugobowne did you figure it out?

**Comment by hugobowne** [comment]
test_function_definition('shout', body = lambda: test_object_after_expression('shout_word')) works!

@vincentvankrunkelsven 

i agree we should discuss a more more "object-oriented-ish" python sct with filip :-)
